from __future__ import annotations

import pandas as pd

from src.dashboard_helpers import DATA_DIR, TABLE_DIR, read_csv, read_indexed_csv, safe_read_csv


def load_project_data() -> dict[str, pd.DataFrame]:
    """Load project inputs and precomputed academic outputs used by the dashboard."""
    return {
        "raw": read_indexed_csv(DATA_DIR / "raw_fred_macro.csv"),
        "model": read_indexed_csv(DATA_DIR / "academic_model_data.csv"),
        "dummies": read_indexed_csv(DATA_DIR / "academic_break_dummies.csv"),
        "architecture": read_csv(TABLE_DIR / "academic_final_model_architecture.csv"),
        "ordering": read_csv(TABLE_DIR / "academic_cholesky_ordering.csv"),
        "variable_dictionary": safe_read_csv(TABLE_DIR / "academic_variable_dictionary.csv"),
        "cointegration": safe_read_csv(TABLE_DIR / "academic_pairwise_cointegration.csv"),
        "var_lag_selection": safe_read_csv(TABLE_DIR / "academic_var_lag_selection.csv"),
        "varx_lag_selection": safe_read_csv(TABLE_DIR / "academic_varx_lag_selection.csv"),
        "lag_robustness": safe_read_csv(TABLE_DIR / "academic_var_lag_residual_autocorr_robustness.csv"),
        "ranking": read_csv(TABLE_DIR / "academic_all_model_forecast_ranking.csv"),
        "econ_forecasts": read_indexed_csv(TABLE_DIR / "academic_econometric_inflation_forecasts.csv"),
        "ml_forecasts": read_indexed_csv(TABLE_DIR / "academic_ml_inflation_forecasts.csv"),
        "granger": read_csv(TABLE_DIR / "academic_granger_causality_map.csv"),
        "raw_adf": read_csv(TABLE_DIR / "academic_raw_adf_tests.csv"),
        "transformed_adf": read_csv(TABLE_DIR / "academic_transformed_adf_tests.csv"),
        "var_diag": safe_read_csv(TABLE_DIR / "academic_var_residual_diagnostics.csv"),
        "varx_diag": safe_read_csv(TABLE_DIR / "academic_varx_residual_diagnostics.csv"),
        "var_norm": safe_read_csv(TABLE_DIR / "academic_var_residual_normality.csv"),
        "varx_norm": safe_read_csv(TABLE_DIR / "academic_varx_residual_normality.csv"),
        "var_het": safe_read_csv(TABLE_DIR / "academic_var_heteroskedasticity_tests.csv"),
        "varx_het": safe_read_csv(TABLE_DIR / "academic_varx_heteroskedasticity_tests.csv"),
        "var_sig": safe_read_csv(TABLE_DIR / "academic_var_parameter_significance.csv"),
        "varx_sig": safe_read_csv(TABLE_DIR / "academic_varx_parameter_significance.csv"),
        "var_sig_summary": safe_read_csv(TABLE_DIR / "academic_var_parameter_significance_summary.csv"),
        "varx_sig_summary": safe_read_csv(TABLE_DIR / "academic_varx_parameter_significance_summary.csv"),
        "var_robust": safe_read_csv(TABLE_DIR / "academic_var_parameter_significance_robust.csv"),
        "varx_robust": safe_read_csv(TABLE_DIR / "academic_varx_parameter_significance_robust.csv"),
        "comparison": safe_read_csv(TABLE_DIR / "academic_var_varx_diagnostic_comparison.csv"),
        "multihorizon": safe_read_csv(TABLE_DIR / "academic_multihorizon_forecast_comparison.csv"),
        "dm": safe_read_csv(TABLE_DIR / "academic_diebold_mariano_tests.csv"),
        "crisis": safe_read_csv(TABLE_DIR / "academic_crisis_dummy_robustness.csv"),
        "expanding": safe_read_csv(TABLE_DIR / "academic_expanding_window_robustness.csv"),
        "regime": safe_read_csv(TABLE_DIR / "academic_regime_split_comparison.csv"),
        "irf_robustness": safe_read_csv(TABLE_DIR / "academic_irf_robustness_summary.csv"),
        "fevd": safe_read_csv(TABLE_DIR / "academic_fevd_selected_horizons.csv"),
        "varx_scenario": safe_read_csv(TABLE_DIR / "academic_varx_scenario_response.csv"),
        "optimized_specs": safe_read_csv(TABLE_DIR / "optimized_final_model_specs.csv"),
        "optimized_ranking": safe_read_csv(TABLE_DIR / "optimized_candidate_model_ranking.csv"),
        "optimized_crisis": safe_read_csv(TABLE_DIR / "optimized_crisis_dummy_search.csv"),
        "optimized_var_metrics": safe_read_csv(TABLE_DIR / "optimized_final_var_metrics.csv"),
        "optimized_varx_metrics": safe_read_csv(TABLE_DIR / "optimized_final_varx_metrics.csv"),
        "optimized_var_granger": safe_read_csv(TABLE_DIR / "optimized_final_var_granger.csv"),
        "optimized_varx_granger": safe_read_csv(TABLE_DIR / "optimized_final_varx_granger.csv"),
        "optimized_var_residual_tests": safe_read_csv(TABLE_DIR / "optimized_final_var_residual_tests.csv"),
        "optimized_varx_residual_tests": safe_read_csv(TABLE_DIR / "optimized_final_varx_residual_tests.csv"),
        "var_irf_ci": safe_read_csv(TABLE_DIR / "academic_var_irf_confidence_intervals.csv"),
        "cholesky_robustness": safe_read_csv(TABLE_DIR / "academic_cholesky_ordering_robustness.csv"),
        "restricted_var_restrictions": safe_read_csv(TABLE_DIR / "restricted_var_restrictions.csv"),
        "restricted_var_metrics": safe_read_csv(TABLE_DIR / "restricted_var_metrics.csv"),
        "restricted_var_diagnostics": safe_read_csv(TABLE_DIR / "restricted_var_residual_diagnostics.csv"),
        "restricted_var_forecasts": safe_read_csv(TABLE_DIR / "restricted_var_forecast_comparison.csv"),
        "restricted_varx_restrictions": safe_read_csv(TABLE_DIR / "restricted_varx_restrictions.csv"),
        "restricted_varx_metrics": safe_read_csv(TABLE_DIR / "restricted_varx_metrics.csv"),
        "restricted_varx_diagnostics": safe_read_csv(TABLE_DIR / "restricted_varx_residual_diagnostics.csv"),
        "restricted_varx_forecasts": safe_read_csv(TABLE_DIR / "restricted_varx_forecast_comparison.csv"),
        "fedfunds_stationarity": safe_read_csv(TABLE_DIR / "fedfunds_stationarity_robustness.csv"),
        "var_fedfunds_level_diff": safe_read_csv(TABLE_DIR / "var_fedfunds_level_vs_diff_comparison.csv"),
        "varx_fedfunds_level_diff": safe_read_csv(TABLE_DIR / "varx_fedfunds_level_vs_diff_comparison.csv"),
        "var_diff_metrics": safe_read_csv(TABLE_DIR / "var_diff_fedfunds_model_metrics.csv"),
        "var_diff_diagnostics": safe_read_csv(TABLE_DIR / "var_diff_fedfunds_residual_diagnostics.csv"),
        "var_diff_granger": safe_read_csv(TABLE_DIR / "var_diff_fedfunds_granger.csv"),
        "var_diff_irf": safe_read_csv(TABLE_DIR / "var_diff_fedfunds_irf_summary.csv"),
        "var_diff_fevd": safe_read_csv(TABLE_DIR / "var_diff_fedfunds_fevd_summary.csv"),
        "varx_diff_metrics": safe_read_csv(TABLE_DIR / "varx_diff_fedfunds_model_metrics.csv"),
        "varx_diff_diagnostics": safe_read_csv(TABLE_DIR / "varx_diff_fedfunds_residual_diagnostics.csv"),
        "varx_diff_scenario": safe_read_csv(TABLE_DIR / "varx_diff_fedfunds_scenario_response.csv"),
        "fedfunds_level_diff_stationarity": safe_read_csv(TABLE_DIR / "fedfunds_level_vs_diff_stationarity.csv"),
        "fedfunds_level_diff_var": safe_read_csv(TABLE_DIR / "fedfunds_level_vs_diff_var_comparison.csv"),
        "fedfunds_level_diff_varx": safe_read_csv(TABLE_DIR / "fedfunds_level_vs_diff_varx_comparison.csv"),
        "fedfunds_baseline_decision": safe_read_csv(TABLE_DIR / "fedfunds_level_vs_diff_final_baseline_decision.csv"),
        "d_fedfunds_var_lag_selection": safe_read_csv(TABLE_DIR / "d_fedfunds_var_lag_selection.csv"),
        "d_fedfunds_varx_lag_selection": safe_read_csv(TABLE_DIR / "d_fedfunds_varx_lag_selection.csv"),
        "d_fedfunds_var_metrics": safe_read_csv(TABLE_DIR / "d_fedfunds_var_metrics.csv"),
        "d_fedfunds_varx_metrics": safe_read_csv(TABLE_DIR / "d_fedfunds_varx_metrics.csv"),
        "d_fedfunds_granger": safe_read_csv(TABLE_DIR / "d_fedfunds_granger.csv"),
        "d_fedfunds_irf": safe_read_csv(TABLE_DIR / "d_fedfunds_irf_summary.csv"),
        "d_fedfunds_fevd": safe_read_csv(TABLE_DIR / "d_fedfunds_fevd_summary.csv"),
        "d_fedfunds_forecast_comparison": safe_read_csv(TABLE_DIR / "d_fedfunds_forecast_comparison.csv"),
    }


def modeling_frame(model_df: pd.DataFrame, dummies: pd.DataFrame) -> pd.DataFrame:
    """Combine transformed model variables with break dummies for VARX experiments."""
    return pd.concat([model_df, dummies], axis=1)
